### PR TITLE
fix(footer): L3-3829 fix subscribe drawer

### PR DESCRIPTION
**Pull request by scottdickerson**
**Jira ticket**

[L3-3829](https://phillipsauctions.atlassian.net/browse/TICKET-ID)

**Screenshots**
| Before | After |
| ------ | ----- |
| image | image |

**Summary**

The change to apply styles in the `seldonProvider.scss` rather than the `reset.scss` caused this problem as well as others. This change undoes that and moves the styles back to `reset.scss`.  This change reverts all the SeldonProvider styling changes made in the earlier 8ff6379bb51e0a5d9560561549b256d3265e4588 and fixes the one SearchResults highlighting issue by applying the styles.  

**Change List (describe the changes made to the files)**

- change(seldonprovider): remove the seldonProvider.scss
- change(SeldonProvider): move to `/SeldonProvider` subdirectory
- change(reset): restore the reset.scss changes

**Acceptance Test (how to verify the PR)**

- `npm link @phillips/seldon` into Remix
- Test Footer subscribe option

**Regression Test**

- Test Search Results to ensure they're still highlighting in Remix on match

**Evidence of testing**

- Post logs, screenshots, etc

**Things to look for during review**

- [ ] PR title should correctly describe the most significant type of commit. I.e. `feat(scope): ...` if a `minor` release should be triggered.
- [ ] All commit messages follow convention and are appropriate for the changes
- [ ] All references to `phillips` class prefix are using the prefix variable
- [ ] All major areas have a `data-testid` attribute.
- [ ] Document all props with jsdoc comments
- [ ] All strings should be translatable.
- [ ] Unit tests should be written and should have a coverage of 90% or higher in all areas.

New Components

- [ ] Are there any [accessibility considerations](https://www.w3.org/WAI/ARIA/apg/patterns/) that need to be taken into account and tested?
- [ ] Default story called "Playground" should be created for all new components
- [ ] Create a jsdoc comment that has an Overview section and a link to the Figma design for the component
- [ ] Export the component and its typescript type from the `index.ts` file
- [ ] Import the component scss file into the `componentStyles.scss` file.

[L3-3829]: https://phillipsauctions.atlassian.net/browse/L3-3829?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by adietrich3074 — APPROVED** [review]
👍

**Review by davidicus — APPROVED** [review]

**Review by davidicus — CHANGES_REQUESTED** [review]
Seeing stories broken
image

**Comment by scottdickerson** [comment]
> Seeing stories broken image
> 
> The [one](https://phillips-seldon.netlify.app/?path=/story/components-contentpeek--custom-text) in production

Hmm, I don't see that in mine: 
image

**Pull request merged**
