### PR TITLE
fix(header): L3-4097 - fix padding and transition bug

### PR DESCRIPTION
**Pull request by davidicus**
**Jira ticket**

[L3-4097](https://phillipsauctions.atlassian.net/browse/L3-4097)

**Screenshots**
| Before | After |
| ------ | ----- |
| image | image |

**Summary**

This PR addresses a few discrepancies between implementation and Figma design. It also addresses a transition bug on resize.

**Change List (describe the changes made to the files)**

- Added media query to only show underlines for header links on desktop in `src/components/Link/_link.scss`
- Corrected token value in `src/components/Navigation/NavigationList/_navigationList.scss` to match figma
- Removed border for bottom link accordion and added the one for language accordion item. I also swapped out units for transition bug in `src/site-furniture/Header/_header.scss`
- change(accordionitem): add special class for locked content with padding and make the "Large" variant have a larger click target on the trigger
- change(_accordion.scss): move the bottom margin from the overall accordion item, to the individual "label" and "content" so we can adjust for the different open/closed state and the locked vs unlocked content
- change(Header): use Large AccordionVariant
- change(navigationList): remove the item padding as it's no longer needed
- change(languageSelector): remove the nav__list padding and use the accordion padding. use Large AccordionVariant
- change(footer): remove the item padding and ul padding as it's no longer needed. Use the OOTB label padding. use Large AccordionVariant

**Acceptance Test (how to verify the PR)**

- Make sure header story matches the [figma](https://www.figma.com/design/hMu9IWH5N3KamJy8tLFdyV/EASEL-Compendium%3A-Tokens%2C-Components-%26-Patterns?node-id=10572-6185&node-type=canvas&m=dev)

**Regression Test**

- Rest of header, like the desktop view, should all look normal
- Mobile Header and Mobile Footer and Mobile Language Selector should look correct

**Things to look for during review**

- [ ] PR title should correctly describe the most significant type of commit. I.e. `feat(scope): ...` if a `minor` release should be triggered.
- [ ] All commit messages follow convention and are appropriate for the changes
- [ ] All references to `phillips` class prefix are using the prefix variable
- [ ] All major areas have a `data-testid` attribute.
- [ ] Document all props with jsdoc comments
- [ ] All strings should be translatable.
- [ ] Unit tests should be written and should have a coverage of 90% or higher in all areas.

New Components

- [ ] Are there any [accessibility considerations](https://www.w3.org/WAI/ARIA/apg/patterns/) that need to be taken into account and tested?
- [ ] Default story called "Playground" should be created for all new components
- [ ] Create a jsdoc comment that has an Overview section and a link to the Figma design for the component
- [ ] Export the component and its typescript type from the `index.ts` file
- [ ] Import the component scss file into the `componentStyles.scss` file.

[L3-4097]: https://phillipsauctions.atlassian.net/browse/L3-4097?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by adietrich3074 — APPROVED** [review]
Looks great! Thanks for the help on the header 😄

**Comment by scottdickerson** [comment]
one thing I'm noticing is that the full Nav Trigger for Calendar is a clickable target, but only a small part of the Auctions or Department is clickable.  It seems like the whole area for the accordions (in addition to padding) should be clickable

**Review by scottdickerson — CHANGES_REQUESTED** [review]
Accordion clickability is confusing at these larger sizes

**Review by scottdickerson — APPROVED** [review]
LGTM

**Pull request merged**
