### PR TITLE
fix(build): L3-2289 - add entry for utils

### PR DESCRIPTION
**Pull request by davidicus**
**Jira ticket**

[L3-2289](https://phillipsauctions.atlassian.net/browse/L3-2289)

**Screenshots**
| Before | After |
| ------ | ----- |
| image| image |

**Summary**

Import the the utils file into our index entry file.

**Change List (describe the changes made to the files)**

- Change import to include other util functions. 

**Acceptance Test (how to verify the PR)**

- Run the build command locally and make sure you see the `emailValidation` function being exported. 

**Things to look for during review**

- [ ] Make sure all references to `phillips` class prefix is using the prefix variable
- [ ] All major areas have a `data-testid` attribute.
- [ ] Document all props with jsdoc comments
- [ ] All strings should be translatable.
- [ ] Unit test should be written and should have a coverage of 90% or higher in all areas.
- [ ] PR should link and close out an existing issue
- [ ] Make sure all commits messages follow convention and are appropriate for the changes

New Components

- [ ] Default story called "Playground" should be created for all new components
- [ ] Create a jsdoc comment that has an Overview section and a link to the Figma design for the component
- [ ] Export the component and its typescript type from the `index.ts` file

[L3-2289]: https://phillipsauctions.atlassian.net/browse/L3-2289?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by scottdickerson — COMMENTED** [review]
why did you decide to do it this way instead of just adding the utils export to `index.ts`?

**Comment by davidicus** [comment]
> why did you decide to do it this way instead of just adding the utils export to `index.ts`? I think going forward we might want to have multiple other subdirectories exported and I'm not sure that we would want to change the vite.config.ts for each one..

I am not super opinionated on this. I guess, I would rather config not be updated often. Good call, I will change.

**Comment by davidicus** [comment]
I used a star import here. Maybe anything in this utils folder should be a utility that can be broadly applied. And then any scoped utils are done like we did for link.

**Pull request merged**
